name = "TGP Simple Cockpit Slew"
prefix = "tgp"
mainprefix = "z"

[properties]
author = "Ampersand"
url = "https://github.com/ampersand38/tgp-simple-cockpit-slew"

[files]
include = [
    "AUTHORS.txt",
    "LICENSE",
    "logo_ampersand_ca.paa",
    "mod.cpp",
    "README.md"
]

[asc]
enabled = true
